services:
  # auth-db
  auth-db:
    image: mongo:6.0
    container_name: auth-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27018:27017"
    volumes:
      - auth-db-data:/data/db
    networks:
      - app-network

  user-db:
    image : mongo:6.0
    container_name: user-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user123
    ports:
      - "27019:27017"
    volumes:
      - user-db-data:/data/db
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DEBUG: "true"
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@auth-db:27017/authdb?authSource=admin
    depends_on:
      - auth-db
    networks:
      - app-network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://user:user123@user-db:27017/userdb?authSource=admin
    depends_on:
      - user-db
    networks:
      - app-network
networks:
  app-network:

volumes:
  auth-db-data:
  user-db-data:
  product-db-data: