version: '3.9'

services:
  auth-db:
    image: mongo:6.0
    container_name: auth-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27021:27017"
    networks:
      - app-network

  user-db:
    image: mongo:6.0
    container_name: user-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user123
    ports:
      - "27022:27017"
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@auth-db:27017/auth_db?authSource=admin
    depends_on:
      - auth-db
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8083:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://user:user123@user-db:27017/user_db?authSource=admin
    depends_on:
      - user-db
    networks:
      - app-network

networks:
  app-network:
