spring.application.name=lets-play

spring.mongodb.uri=mongodb://localhost:27017/letsplay_db
spring.mongodb.database=letsplay_db

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=dzorjpgcr
cloudinary.api-key=557892835181922
cloudinary.api-secret=SeNKmpmScx1EOrpikV8sPpkbq4o


# Server
# server.port=8443

# HTTPS (Self-signed cert for development)
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=your-password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=letsplay
