spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://user:user@localhost:27018/userdb?authSource=admin
  # jackson:
  #     default-property-inclusion: non_null

server:
  port: 8081
