spring:
    application:
        name: user-service
    # mongodb:
    #     database: auth_db
    #     uri: ${SPRING_DATA_MONGODB_URI}
    jackson:
        default-property-inclusion: non_null

server:
    port: 8080